version: '3'
services:
  db:
    image: postgres:16.8
    container_name: my_postgres
    environment:
      POSTGRES_DB: stars_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: my_spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stars_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    env_file: # .env 파일 로드
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
